[profile.default]
solc_version = "0.8.28"
evm_version = "paris"
optimizer = true
optimizer_runs = 10_000_000

[rpc_endpoints]
arb = "https://arbitrum.drpc.org"
avax = "https://avalanche.drpc.org"
base = "https://mainnet.base.org"
bsc = "https://bsc-dataseed1.defibit.io"
gnosis = "https://rpc.gnosischain.com"
eth = "https://rpc.mevblocker.io"
op = "https://op-pokt.nodies.app"
polygon = "https://rpc.ankr.com/polygon"
